# Generated by issues_md_to_py.py from _temp/issues-noted.md -- do not hand-edit.
# Each M1 is an exact source substring; issues_batch_replace.py applies it verbatim.
# MULTI issues intentionally match several places (all changed). SUBMODULE issues are
# committed inside their submodule by issues_batch_replace.py.
# See issues_report.md for AMBIGUOUS / UNRESOLVED / RESOLVED issues to handle by hand.
ISSUES_FOUND = [
    ('example, `You` object',
     'example, `the You` object',
     'oop/objects/what/text.md',
     'Missing article before named object'),  # [grammar] The sentence needs the definite article before the named object.
    ('from `Person` class.',
     'from `the Person` class.',
     'oop/inheritance/what/text.md',
     'Missing article before class name'),  # [grammar] A reference to the named class needs the definite article.
    ('can login to',
     'can log in to',
     'specifyingRequirements/userStories/details/text.md',
     'Incorrect verb form in user story'),  # [grammar] `login` is a noun here; the verb form is `log in`.
    ('reasonably low risk estimate',
     'reasonably low-risk estimate',
     'specifyingRequirements/userStories/usage/text.md',
     'Missing hyphen in compound modifier'),  # [punctuation] `low-risk` is a compound modifier before `estimate` and should be hyphenated.
    ('module is harder**',
     'module are harder**',
     'designFundamentals/coupling/what/text.md',
     'Singular verb with a compound subject'),  # [grammar] `Testing and reuse` is a compound subject and requires the plural verb `are`.
    ('notation used in the',
     'notation in the',
     'common/definitions.md',
     'Repeated use of “used”'),  # [concision] `used` is repeated unnecessarily. The first occurrence already describes the notation's prevalence.
    ('comprising of 100 squares.',
     'comprising 100 squares.',
     'uml/classDiagrams/associationsAsAttributes/what/text.md',
     'Incorrect preposition after “comprising”'),  # [grammar] `Comprising` takes its object directly; omit `of`.
    ('Role_',
     'Role_s',
     'uml/classDiagrams/associations/roles/text.md',
     'Singular association-role label with plural verb'),  # [grammar] The plural verb `are` requires the plural noun `Roles`.
    ('point of time.**',
     'point in time.**',
     'uml/objectDiagrams/introduction/text.md',
     'Incorrect idiom for a moment in time'),  # [phrasing] The standard idiom is `at a given point in time`.
    ('uses _ref frame_',
     'uses _a ref frame_',
     'uml/sequenceDiagrams/referenceFrames/text.md',
     'Missing article before “ref frame”'),  # [grammar] The singular count noun `ref frame` needs an article.
    ('to Logic API:',
     'to the Logic API:',
     'modeling/modelingASolution/intermediate/text.md',
     'Missing articles in API reference'),  # [grammar] A reference to the specific `Logic API` requires the definite article.
    ('a different purpose other',
     'a purpose other',
     'codeQuality/avoidShortcuts/basic/dontRecycleVarsOrParams/text.md',
     'Incorrect “other than” construction'),  # [grammar] `For a different purpose other than` is ungrammatical. Use `for a purpose other than`.
    ('3, .... n',
     '3, ..., n',
     'testCaseDesign/introduction/what/text.md',
     'Four-dot ellipsis'),  # [punctuation] The ellipsis has four dots; use the standard three-dot ellipsis.
    ('does parsing of the user commands as well as interacting',
     'parses user commands as well as interacts',
     'principles/singleResponsibilityPrinciple/text.md',
     'Faulty parallelism in class responsibilities'),  # [grammar] `does parsing` and `interacting` are not parallel. Use matching verbs.
    ('considered as a successful',
     'considered a successful',
     'cppToJava/gettingStarted/helloWorld/text.md',
     'Unnecessary “as” after “considered”'),  # [grammar] `Considered` takes its complement directly in this construction.
    ('-- and use it in',
     '-- and uses it in',
     'cppToJava/objects/usingObjects/text.md',
     'Singular verb needed after “example”'),  # [grammar] The singular subject `This example` requires `uses`.
    ('exceptions In Java:**',
     'exceptions in Java:**',
     'cppToJava/exceptions/what/text.md',
     'Incorrect capitalization of a preposition'),  # [punctuation] The preposition `in` should not be capitalized in the middle of the sentence.
    ('`fail()`',
     '`the fail()`',
     'cppToJava/junit/basic/text.md',
     'Missing article before “fail() line”'),  # [grammar] The singular count noun `line` needs the definite article.
]
